#git remote add                           https://github.com//spbetu_os_2022_0381.git            # 
#git remote add                           https://github.com//spbetu_os_2022_0381.git            # 
#git remote add                           https://github.com//spbetu_os_2022_0381.git            # 
#git remote add                           https://github.com//spbetu_os_2022_0381.git            # 
#git remote add                           https://github.com//spbetu_os_2022_0381.git            # 
#git remote add                           https://github.com//spbetu_os_2022_0381.git            # 
#git remote add                           https://github.com//spbetu_os_2022_0381.git            # 
#git remote add                           https://github.com//spbetu_os_2022_0381.git            # 
#git remote add                           https://github.com//spbetu_os_2022_0381.git            # 
#git remote add                           https://github.com//spbetu_os_2022_0381.git            # 
#git remote add                           https://github.com//spbetu_os_2022_0381.git            # 
#git remote add                           https://github.com//spbetu_os_2022_0381.git            # 
#git remote add                           https://github.com//spbetu_os_2022_0381.git            # 
#git remote add                           https://github.com//spbetu_os_2022_0381.git            # 
#git remote add                           https://github.com//spbetu_os_2022_0381.git            # 
#git remote add                           https://github.com//spbetu_os_2022_0381.git            # 
#git remote add                           https://github.com//spbetu_os_2022_0381.git            # 
#git remote add                           https://github.com//spbetu_os_2022_0381.git            # 
#git remote add                           https://github.com//spbetu_os_2022_0381.git            # 
#git remote add                           https://github.com//spbetu_os_2022_0381.git            # 
#git remote add                           https://github.com//spbetu_os_2022_0381.git            # 
#git remote add                           https://github.com//spbetu_os_2022_0381.git            # 
#git remote add                           https://github.com//spbetu_os_2022_0381.git            # 
#git remote add                           https://github.com//spbetu_os_2022_0381.git            # 
#git remote add                           https://github.com//spbetu_os_2022_0381.git            # 
#git remote add                           https://github.com//spbetu_os_2022_0381.git            # 
#git remote add                           https://github.com//spbetu_os_2022_0381.git            # 
#git remote add                           https://github.com//spbetu_os_2022_0381.git            # 
#git remote add                           https://github.com//spbetu_os_2022_0381.git            # 
#git remote add                           https://github.com//spbetu_os_2022_0381.git            # 
